### ISSUE TITLE
Creating singletons doesn't work

### ISSUE THREAD

**Issue by rico-et22** [onenorth/keystone-singleton#1]
Hello,
I've properly set up a singleton list in Keystone 4.0 (stable), but the plugin can't create an item in it - there's an error like `SINGLETON: Could not create 'Single'.`

What's wrong with that? Maybe this plugin can't handle newer versions?

**Comment by ryan-haskell** [comment]
Hey there, @rico-et22 !

It's possible that the latest KeystoneJS version doesn't support this plugin, we are using this on internal projects using `4.0.0-beta.5`.

This plugin doesn't have any official releases, and while it fits our specific use-case, I would not recommend using it in production code 😄 

I've updated the README.md so that I don't mislead fellow KeystoneJS developers!

---

That being said, I'd love to help you with your problem! The code that comes before that error message tries to create an empty document in Mongoose using `Model.create({})`.

The plugin is small and simple, and you can [check it out here](https://github.com/onenorth/keystone-singleton/blob/master/index.js#L56).

If you have __any `required` fields__ in your `Single` model (that do not have a `default` property set), `Model.create` will fail and lead to that error message.

---

I hope that helps! And although I won't be able to support the community's use of this plugin, you're definitely welcome to join [a Chicago digital agency that is using it in production](https://www.onenorth.com/careers). 😄 

Have a great weekend!
Ryan

**Comment by rico-et22** [comment]
That was it, I've created a clone of the default Post model with one required field and that's made that error.
It would be nice to add these informations to the docs:

-  Having required fields will throw an error,
-  a default title should be specified in the model.

Thanks for help!
